default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USER") { "parser_dev" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "p@ssword123" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: parser_development


test:
  <<: *default
  database: parser_test

production:
  <<: *default
  database: parser_production
